services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: healthcare_db
      POSTGRES_USER: healthcare_user
      POSTGRES_PASSWORD: healthcare_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healthcare_user -d healthcare_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://healthcare_user:healthcare_password@postgres:5432/healthcare_db
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-here}
      - JWT_ACCESS_TOKEN_LIFETIME=${JWT_ACCESS_TOKEN_LIFETIME:-15}
      - JWT_REFRESH_TOKEN_LIFETIME=${JWT_REFRESH_TOKEN_LIFETIME:-1440}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./auth-service:/app

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DATABASE_SERVICE_URL=http://database-service:8004
      - AUTH_SERVICE_URL=http://auth-service:8001
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-here}
    depends_on:
      - database-service
      - auth-service
    volumes:
      - ./patient-service:/app

  clinician-service:
    build:
      context: ./clinician-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - DATABASE_SERVICE_URL=http://database-service:8004
      - AUTH_SERVICE_URL=http://auth-service:8001
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-here}
    depends_on:
      - database-service
      - auth-service
    volumes:
      - ./clinician-service:/app

  database-service:
    build:
      context: ./database-service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql://healthcare_user:healthcare_password@postgres:5432/healthcare_db
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-here}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./database-service:/app
      - ./cancer_types.json:/app/cancer_types.json:ro

  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    environment:
      - DATABASE_SERVICE_URL=http://database-service:8004
      - AUTH_SERVICE_URL=http://auth-service:8001
      - PATIENT_SERVICE_URL=http://patient-service:8002
      - CLINICIAN_SERVICE_URL=http://clinician-service:8003
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-here}
    depends_on:
      - database-service
      - auth-service
    volumes:
      - ./admin-service:/app

  file-service:
    build:
      context: ./file-service
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    environment:
      - DATABASE_SERVICE_URL=http://database-service:8004
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-here}
      - FILE_STORAGE_PATH=/app/media/encrypted_files
      - MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB:-100}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
    depends_on:
      - database-service
    volumes:
      - ./file-service:/app
      - file-storage:/app/media/encrypted_files

  embedding-service:
    build:
      context: ./embedding-service
      dockerfile: Dockerfile
    ports:
      - "8007:8007"
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-here}
      - DATABASE_SERVICE_URL=http://database-service:8004
      - AUTH_SERVICE_URL=http://auth-service:8001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL:-text-embedding-ada-002}
      - OPENAI_MAX_TOKENS_PER_CHUNK=${OPENAI_MAX_TOKENS_PER_CHUNK:-8000}
      - MAX_CONCURRENT_EMBEDDINGS=${MAX_CONCURRENT_EMBEDDINGS:-3}
      - EMBEDDING_RETRY_MAX_ATTEMPTS=${EMBEDDING_RETRY_MAX_ATTEMPTS:-3}
      - EMBEDDING_RETRY_DELAY=${EMBEDDING_RETRY_DELAY:-60}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-52428800}
      - ALLOWED_FILE_TYPES=${ALLOWED_FILE_TYPES:-.pdf,.txt,.doc,.docx}
    depends_on:
      - database-service
      - auth-service
    volumes:
      - ./embedding-service:/app
      - embedding-temp:/app/media/temp_files

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - patient-service
      - clinician-service
      - database-service
      - admin-service
      - file-service
      - embedding-service
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - patient-static:/patient-static
      - auth-static:/auth-static
      - admin-static:/admin-static

  pgadmin:
    image: dpage/pgadmin4:9.5.0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@healthcare.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
  patient-static:
  auth-static:
  admin-static:
  file-storage:
  embedding-temp: